-- SHAFX Stage 7 identity + automatic security schema
-- Run this once in the Supabase SQL Editor for the SHAFX project.

create table if not exists public.shafx_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  status text not null default 'active' check (status in ('active','suspended','banned')),
  simulator_account_id text unique not null default ('SIM-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  security_state text not null default 'normal' check (security_state in ('normal','elevated','blocked')),
  last_login_at timestamptz,
  failed_login_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.shafx_profiles enable row level security;
drop policy if exists "Users can read own SHAFX profile" on public.shafx_profiles;
create policy "Users can read own SHAFX profile" on public.shafx_profiles for select using (auth.uid() = id);
drop policy if exists "Users can update own display name" on public.shafx_profiles;
create policy "Users can update own display name" on public.shafx_profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create or replace function public.handle_new_shafx_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.shafx_profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_shafx on auth.users;
create trigger on_auth_user_created_shafx after insert on auth.users for each row execute procedure public.handle_new_shafx_user();

create or replace function public.set_shafx_profile_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists on_shafx_profile_updated on public.shafx_profiles;
create trigger on_shafx_profile_updated before update on public.shafx_profiles for each row execute procedure public.set_shafx_profile_updated_at();

create table if not exists public.shafx_security_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  decision text not null check (decision in ('allow','block','deny')),
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  fingerprint text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.shafx_security_events enable row level security;
create index if not exists shafx_security_events_user_created_idx on public.shafx_security_events (user_id, created_at desc);
create index if not exists shafx_security_events_created_idx on public.shafx_security_events (created_at desc);

alter table public.shafx_profiles add column if not exists risk_score integer not null default 0;
alter table public.shafx_profiles add column if not exists security_state text not null default 'normal';
alter table public.shafx_profiles add column if not exists last_login_at timestamptz;
alter table public.shafx_profiles add column if not exists failed_login_count integer not null default 0;

-- Bot entitlement is server-controlled. Clients can read their own plan but cannot change it.
create table if not exists public.shafx_bot_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'FREE' check (plan in ('FREE','REGULAR','PRO')),
  updated_at timestamptz not null default now()
);
alter table public.shafx_bot_entitlements enable row level security;
drop policy if exists "Users can read own bot entitlement" on public.shafx_bot_entitlements;
create policy "Users can read own bot entitlement" on public.shafx_bot_entitlements for select using (auth.uid() = user_id);

create table if not exists public.shafx_bot_usage (
  user_id uuid primary key references auth.users(id) on delete cascade,
  run_id text,
  used_cycle_units integer not null default 0 check (used_cycle_units >= 0),
  updated_at timestamptz not null default now()
);
alter table public.shafx_bot_usage enable row level security;
drop policy if exists "Users can read own bot usage" on public.shafx_bot_usage;
create policy "Users can read own bot usage" on public.shafx_bot_usage for select using (auth.uid() = user_id);

create or replace function public.handle_new_shafx_user_bot_defaults()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.shafx_bot_entitlements(user_id, plan) values (new.id, 'FREE') on conflict (user_id) do nothing;
  insert into public.shafx_bot_usage(user_id, used_cycle_units) values (new.id, 0) on conflict (user_id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created_shafx_bot on auth.users;
create trigger on_auth_user_created_shafx_bot after insert on auth.users for each row execute procedure public.handle_new_shafx_user_bot_defaults();
insert into public.shafx_bot_entitlements(user_id, plan) select id, 'FREE' from auth.users on conflict (user_id) do nothing;
insert into public.shafx_bot_usage(user_id, used_cycle_units) select id, 0 from auth.users on conflict (user_id) do nothing;
