-- SHAFX Stage 7 identity + automatic security schema
-- Run this once in the Supabase SQL Editor for the SHAFX project.

create table if not exists public.shafx_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  status text not null default 'active' check (status in ('active','suspended','banned')),
  simulator_account_id text unique not null default ('SIM-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  security_state text not null default 'normal' check (security_state in ('normal','elevated','blocked')),
  last_login_at timestamptz,
  failed_login_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.shafx_profiles enable row level security;
drop policy if exists "Users can read own SHAFX profile" on public.shafx_profiles;
create policy "Users can read own SHAFX profile" on public.shafx_profiles for select using (auth.uid() = id);
drop policy if exists "Users can update own display name" on public.shafx_profiles;
create policy "Users can update own display name" on public.shafx_profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create or replace function public.handle_new_shafx_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.shafx_profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_shafx on auth.users;
create trigger on_auth_user_created_shafx after insert on auth.users for each row execute procedure public.handle_new_shafx_user();

create or replace function public.set_shafx_profile_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists on_shafx_profile_updated on public.shafx_profiles;
create trigger on_shafx_profile_updated before update on public.shafx_profiles for each row execute procedure public.set_shafx_profile_updated_at();

create table if not exists public.shafx_security_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  decision text not null check (decision in ('allow','block','deny')),
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  fingerprint text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.shafx_security_events enable row level security;
create index if not exists shafx_security_events_user_created_idx on public.shafx_security_events (user_id, created_at desc);
create index if not exists shafx_security_events_created_idx on public.shafx_security_events (created_at desc);

alter table public.shafx_profiles add column if not exists risk_score integer not null default 0;
alter table public.shafx_profiles add column if not exists security_state text not null default 'normal';
alter table public.shafx_profiles add column if not exists last_login_at timestamptz;
alter table public.shafx_profiles add column if not exists failed_login_count integer not null default 0;

-- Bot entitlement is server-controlled. Clients can read their own plan but cannot change it.
create table if not exists public.shafx_bot_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'FREE' check (plan in ('FREE','REGULAR','PRO')),
  subscription_status text not null default 'active' check (subscription_status in ('inactive','trialing','active','past_due','canceled','unpaid','paused')),
  subscription_ends_at timestamptz,
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  updated_at timestamptz not null default now()
);
alter table public.shafx_bot_entitlements enable row level security;
drop policy if exists "Users can read own bot entitlement" on public.shafx_bot_entitlements;
create policy "Users can read own bot entitlement" on public.shafx_bot_entitlements for select using (auth.uid() = user_id);

create table if not exists public.shafx_bot_usage (
  user_id uuid primary key references auth.users(id) on delete cascade,
  run_id text,
  used_cycle_units integer not null default 0 check (used_cycle_units >= 0),
  current_unit_round integer not null default 0 check (current_unit_round between 0 and 5),
  usage_day date not null default ((now() at time zone 'UTC')::date),
  updated_at timestamptz not null default now()
);
alter table public.shafx_bot_usage enable row level security;
drop policy if exists "Users can read own bot usage" on public.shafx_bot_usage;
create policy "Users can read own bot usage" on public.shafx_bot_usage for select using (auth.uid() = user_id);
create index if not exists shafx_bot_usage_day_idx on public.shafx_bot_usage (usage_day);

create or replace function public.handle_new_shafx_user_bot_defaults()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.shafx_bot_entitlements(user_id, plan, subscription_status) values (new.id, 'FREE', 'active') on conflict (user_id) do nothing;
  insert into public.shafx_bot_usage(user_id, used_cycle_units, current_unit_round, usage_day) values (new.id, 0, 0, (now() at time zone 'UTC')::date) on conflict (user_id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created_shafx_bot on auth.users;
create trigger on_auth_user_created_shafx_bot after insert on auth.users for each row execute procedure public.handle_new_shafx_user_bot_defaults();
insert into public.shafx_bot_entitlements(user_id, plan, subscription_status) select id, 'FREE', 'active' from auth.users on conflict (user_id) do nothing;
insert into public.shafx_bot_usage(user_id, used_cycle_units, current_unit_round, usage_day) select id, 0, 0, (now() at time zone 'UTC')::date from auth.users on conflict (user_id) do nothing;

-- Daily bot allowance: Free=5 units/day, Regular=15 units/day, Pro=unlimited while active.
drop function if exists public.consume_shafx_bot_cycle(uuid,text,integer);
drop function if exists public.consume_shafx_bot_round(uuid,text);
create function public.consume_shafx_bot_round(p_user_id uuid, p_run_id text)
returns table(
  ok boolean,
  plan text,
  used_cycle_units integer,
  max_cycle_units integer,
  usage_day date,
  round_number integer,
  completed_unit boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan text;
  v_used integer;
  v_max integer;
  v_day date := (now() at time zone 'UTC')::date;
  v_current_day date;
  v_run_id text;
  v_round integer;
  v_next_round integer;
  v_completed boolean := false;
begin
  if p_run_id is null or p_run_id not like 'v3-%' then
    raise exception 'invalid bot session';
  end if;

  select case
    when e.plan in ('PRO','REGULAR')
      and e.subscription_status in ('trialing','active')
      and (e.subscription_ends_at is null or e.subscription_ends_at > now())
    then e.plan
    else 'FREE'
  end
  into v_plan
  from public.shafx_bot_entitlements e
  where e.user_id = p_user_id;

  if v_plan is null then v_plan := 'FREE'; end if;
  v_max := case v_plan when 'PRO' then null when 'REGULAR' then 15 else 5 end;

  insert into public.shafx_bot_usage(user_id, run_id, used_cycle_units, current_unit_round, usage_day)
  values (p_user_id, p_run_id, 0, 0, v_day)
  on conflict (user_id) do nothing;

  select u.used_cycle_units, u.usage_day, u.run_id, u.current_unit_round
  into v_used, v_current_day, v_run_id, v_round
  from public.shafx_bot_usage u
  where u.user_id = p_user_id
  for update;

  if v_current_day is distinct from v_day or coalesce(v_run_id, '') not like 'v3-%' then
    v_used := 0;
    v_round := 0;
    update public.shafx_bot_usage
    set usage_day = v_day,
        run_id = p_run_id,
        used_cycle_units = 0,
        current_unit_round = 0,
        updated_at = now()
    where user_id = p_user_id;
  end if;

  if v_max is not null and v_used >= v_max then
    return query select false, v_plan, v_used, v_max, v_day, 5, false;
    return;
  end if;

  v_next_round := v_round + 1;
  if v_next_round >= 5 then
    v_completed := true;
    v_used := v_used + 1;
    v_round := 0;
  else
    v_round := v_next_round;
  end if;

  update public.shafx_bot_usage
  set run_id = p_run_id,
      used_cycle_units = v_used,
      current_unit_round = v_round,
      updated_at = now(),
      usage_day = v_day
  where user_id = p_user_id;

  return query
  select true,
         v_plan,
         v_used,
         v_max,
         v_day,
         case when v_completed then 5 else v_round end,
         v_completed;
end;
$$;

revoke execute on function public.consume_shafx_bot_round(uuid,text) from public, anon, authenticated;
grant execute on function public.consume_shafx_bot_round(uuid,text) to service_role;

-- Paid bot catalog and Paystack purchase records.
create table if not exists public.shafx_bot_catalog (
  slug text primary key,
  name text not null,
  description text not null default '',
  price_kes integer not null check (price_kes > 0),
  grant_plan text not null default 'REGULAR' check (grant_plan in ('REGULAR','PRO')),
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shafx_bot_purchases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  bot_slug text not null references public.shafx_bot_catalog(slug),
  provider text not null default 'paystack',
  reference text not null unique,
  amount_kes integer not null check (amount_kes > 0),
  phone text,
  email text not null,
  status text not null default 'pending' check (status in ('pending','success','failed','abandoned')),
  provider_transaction_id text,
  provider_payload jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.shafx_bot_purchases enable row level security;
drop policy if exists "Users can read own bot purchases" on public.shafx_bot_purchases;
create policy "Users can read own bot purchases" on public.shafx_bot_purchases for select using (auth.uid() = user_id);
create index if not exists shafx_bot_purchases_user_created_idx on public.shafx_bot_purchases (user_id, created_at desc);
create index if not exists shafx_bot_purchases_reference_idx on public.shafx_bot_purchases (reference);

create table if not exists public.shafx_user_bots (
  user_id uuid not null references auth.users(id) on delete cascade,
  bot_slug text not null references public.shafx_bot_catalog(slug),
  source_purchase_id uuid references public.shafx_bot_purchases(id) on delete set null,
  active boolean not null default true,
  activated_at timestamptz not null default now(),
  expires_at timestamptz,
  primary key (user_id, bot_slug)
);
alter table public.shafx_user_bots enable row level security;
drop policy if exists "Users can read own bot access" on public.shafx_user_bots;
create policy "Users can read own bot access" on public.shafx_user_bots for select using (auth.uid() = user_id);

create or replace function public.set_shafx_bot_store_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists on_shafx_bot_catalog_updated on public.shafx_bot_catalog;
create trigger on_shafx_bot_catalog_updated before update on public.shafx_bot_catalog for each row execute procedure public.set_shafx_bot_store_updated_at();
drop trigger if exists on_shafx_bot_purchase_updated on public.shafx_bot_purchases;
create trigger on_shafx_bot_purchase_updated before update on public.shafx_bot_purchases for each row execute procedure public.set_shafx_bot_store_updated_at();

create or replace function public.activate_shafx_bot_purchase(p_reference text, p_provider_transaction_id text, p_paid_at timestamptz, p_payload jsonb)
returns table(ok boolean, user_id uuid, bot_slug text)
language plpgsql security definer set search_path = public
as $$
declare
  v_purchase public.shafx_bot_purchases%rowtype;
  v_catalog public.shafx_bot_catalog%rowtype;
begin
  select * into v_purchase from public.shafx_bot_purchases where reference = p_reference for update;
  if not found then return query select false, null::uuid, null::text; return; end if;
  select * into v_catalog from public.shafx_bot_catalog where slug = v_purchase.bot_slug;
  if not found or not v_catalog.active then return query select false, v_purchase.user_id, v_purchase.bot_slug; return; end if;
  if v_purchase.status = 'success' then return query select true, v_purchase.user_id, v_purchase.bot_slug; return; end if;
  update public.shafx_bot_purchases set status='success', provider_transaction_id=coalesce(p_provider_transaction_id, provider_transaction_id), provider_payload=coalesce(p_payload,'{}'::jsonb), paid_at=coalesce(p_paid_at, now()), activated_at=now(), updated_at=now() where id=v_purchase.id;
  insert into public.shafx_user_bots(user_id, bot_slug, source_purchase_id, active, activated_at) values (v_purchase.user_id, v_purchase.bot_slug, v_purchase.id, true, now()) on conflict (user_id, bot_slug) do update set active=true, source_purchase_id=excluded.source_purchase_id, activated_at=excluded.activated_at;
  update public.shafx_bot_entitlements set plan=v_catalog.grant_plan, subscription_status='active', subscription_ends_at=null, provider='paystack', provider_customer_id=null, provider_subscription_id=p_reference, updated_at=now() where user_id=v_purchase.user_id and v_catalog.grant_plan in ('REGULAR','PRO');
  return query select true, v_purchase.user_id, v_purchase.bot_slug;
end;
$$;

-- Production hardening: synchronized with the connected Supabase project.
drop policy if exists "Users can read own SHAFX profile" on public.shafx_profiles;
create policy "Users can read own SHAFX profile" on public.shafx_profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "Users can update own display name" on public.shafx_profiles;
create policy "Users can update own display name" on public.shafx_profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
drop policy if exists "Users can read own bot entitlement" on public.shafx_bot_entitlements;
create policy "Users can read own bot entitlement" on public.shafx_bot_entitlements for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can read own bot usage" on public.shafx_bot_usage;
create policy "Users can read own bot usage" on public.shafx_bot_usage for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can read own bot purchases" on public.shafx_bot_purchases;
create policy "Users can read own bot purchases" on public.shafx_bot_purchases for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can read own bot access" on public.shafx_user_bots;
create policy "Users can read own bot access" on public.shafx_user_bots for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "No direct client access to SHAFX bot catalog" on public.shafx_bot_catalog;
create policy "No direct client access to SHAFX bot catalog" on public.shafx_bot_catalog for all to anon, authenticated using (false) with check (false);
drop policy if exists "No direct client access to SHAFX security events" on public.shafx_security_events;
create policy "No direct client access to SHAFX security events" on public.shafx_security_events for all to anon, authenticated using (false) with check (false);

create index if not exists shafx_bot_purchases_bot_slug_idx on public.shafx_bot_purchases (bot_slug);
create index if not exists shafx_user_bots_bot_slug_idx on public.shafx_user_bots (bot_slug);
create index if not exists shafx_user_bots_source_purchase_id_idx on public.shafx_user_bots (source_purchase_id);
drop index if exists public.shafx_bot_usage_day_idx;
drop index if exists public.shafx_security_events_created_idx;

alter function public.set_shafx_profile_updated_at() set search_path = '';
alter function public.set_shafx_bot_store_updated_at() set search_path = '';
alter function public.handle_new_shafx_user() set search_path = '';
alter function public.handle_new_shafx_user_bot_defaults() set search_path = '';
alter function public.consume_shafx_bot_cycle(uuid, text, integer) set search_path = '';
alter function public.rls_auto_enable() set search_path = 'pg_catalog';
alter function public.activate_shafx_bot_purchase(text, text, timestamptz, jsonb) set search_path = '';

revoke execute on function public.consume_shafx_bot_cycle(uuid, text, integer) from public, anon, authenticated;
revoke execute on function public.handle_new_shafx_user() from public, anon, authenticated;
revoke execute on function public.handle_new_shafx_user_bot_defaults() from public, anon, authenticated;
revoke execute on function public.rls_auto_enable() from public, anon, authenticated;
revoke execute on function public.activate_shafx_bot_purchase(text, text, timestamptz, jsonb) from public, anon, authenticated;
grant execute on function public.consume_shafx_bot_cycle(uuid, text, integer) to service_role;
grant execute on function public.handle_new_shafx_user() to service_role;
grant execute on function public.handle_new_shafx_user_bot_defaults() to service_role;
grant execute on function public.rls_auto_enable() to service_role;
grant execute on function public.activate_shafx_bot_purchase(text, text, timestamptz, jsonb) to service_role;

-- Hosted Auth leaked-password protection is a Supabase Auth setting rather than SQL.
-- Enable it in Authentication -> Providers -> Email on a supported plan.
