import React, { useState } from 'react'
import { Clock, History, ListChecks, XCircle } from 'lucide-react'
import type { TradeOrder } from '../../types'
import { formatCurrency, formatPrice, formatTimestamp } from '../../lib/format'

interface Props { openPositions: TradeOrder[]; pendingOrders: TradeOrder[]; tradeHistory: TradeOrder[]; currentPrice: number; selectedSymbol: string; onClosePosition: (id: string) => void | Promise<void> }
type Tab = 'positions' | 'pending' | 'history'

export const TradesPanel: React.FC<Props> = ({ openPositions, pendingOrders, tradeHistory, currentPrice, selectedSymbol, onClosePosition }) => {
  const [activeTab, setActiveTab] = useState<Tab>('positions')
  const precision = (s: string) => s.includes('JPY') ? 3 : 5
  const data = activeTab === 'positions' ? openPositions : activeTab === 'pending' ? pendingOrders : tradeHistory
  const empty = <div className="flex flex-col items-center justify-center py-8 text-shafx-textMuted"><ListChecks className="mb-2 h-8 w-8 opacity-50" /><p className="text-sm">No records found</p></div>
  return <div className="flex h-full flex-col rounded-lg border border-shafx-border bg-shafx-surface"><div className="flex overflow-x-auto border-b border-shafx-border">{([['positions','Open',openPositions.length,ListChecks],['pending','Pending',pendingOrders.length,Clock],['history','History',tradeHistory.length,History]] as const).map(([key,label,count,Icon]) => <button key={key} type="button" onClick={() => setActiveTab(key)} aria-pressed={activeTab === key} className={`flex min-h-11 items-center gap-2 whitespace-nowrap border-b-2 px-3 text-xs font-medium sm:px-4 sm:text-sm ${activeTab === key ? 'border-shafx-primary text-shafx-primary' : 'border-transparent text-shafx-textMuted hover:text-shafx-text'}`}><Icon className="h-4 w-4" />{label} ({count})</button>)}</div><div className="flex-1 overflow-auto">{data.length === 0 ? empty : <table className="w-full min-w-[820px] text-left text-xs"><thead className="bg-shafx-bg/50 uppercase text-shafx-textMuted"><tr>{['Ticket','Time','Type','Symbol','Volume','Price','S/L','T/P','Profit','Action'].map((h) => <th key={h} className="px-4 py-2">{h}</th>)}</tr></thead><tbody className="divide-y divide-shafx-border">{data.map((trade) => { const p = precision(trade.symbol); const profit = trade.profit ?? 0; const isSelectedOpen = activeTab === 'positions' && trade.status === 'open' && trade.symbol === selectedSymbol; return <tr key={trade.id} className="hover:bg-shafx-surfaceHover"><td className="px-4 py-2 font-mono text-shafx-textMuted">{trade.id}</td><td className="px-4 py-2 text-shafx-textMuted">{formatTimestamp(trade.openTime)}</td><td className={`px-4 py-2 font-semibold ${trade.type === 'BUY' ? 'text-shafx-success' : 'text-shafx-danger'}`}>{trade.type}</td><td className="px-4 py-2 font-medium">{trade.symbol}</td><td className="px-4 py-2 font-mono tabular">{trade.lotSize.toFixed(2)}</td><td className="px-4 py-2 font-mono tabular">{formatPrice(trade.entryPrice,p)}</td><td className="px-4 py-2 font-mono text-shafx-danger tabular">{trade.stopLoss === null ? '—' : formatPrice(trade.stopLoss,p)}</td><td className="px-4 py-2 font-mono text-shafx-success tabular">{trade.takeProfit === null ? '—' : formatPrice(trade.takeProfit,p)}</td><td className={`px-4 py-2 font-mono font-semibold tabular ${profit >= 0 ? 'text-shafx-success' : 'text-shafx-danger'}`}>{profit >= 0 ? '+' : ''}{formatCurrency(profit)}</td><td className="px-4 py-2">{isSelectedOpen ? <button type="button" onClick={() => void onClosePosition(trade.id)} className="inline-flex min-h-10 items-center gap-1 rounded border border-shafx-border px-2 text-xs text-shafx-textMuted hover:border-shafx-danger hover:text-shafx-danger" aria-label={`Close ${trade.id}`}><XCircle className="h-3.5 w-3.5" />Close @ {formatPrice(currentPrice,p)}</button> : '—'}</td></tr> })}</tbody></table>}</div></div>
}
