import React, { useMemo, useState } from 'react'
import { Activity, ChevronDown, Search, Wifi } from 'lucide-react'
import type { MarketPair, Timeframe } from '../../types'
import { TIMEFRAMES } from '../../types'
import { formatPrice } from '../../lib/format'
import { DerivAccountControl } from '../market/DerivAccountControl'

type TerminalView = 'market' | 'agent' | 'history' | 'account'
interface TopNavProps { symbol: string; price: number; pricePrecision: number; timeframe: Timeframe; onTimeframeChange: (tf: Timeframe) => void; pairs: MarketPair[]; onSelectPair: (symbol: string) => void; view?: TerminalView }
const viewTitles: Record<TerminalView, string> = { market: 'Market', agent: 'SHAFX Bot', history: 'Trade history', account: 'Account' }

export const TopNav: React.FC<TopNavProps> = ({ symbol, price, pricePrecision, timeframe, onTimeframeChange, pairs, onSelectPair, view = 'market' }) => {
  const [marketOpen, setMarketOpen] = useState(false); const [accountOpen, setAccountOpen] = useState(false); const [query, setQuery] = useState('')
  const instruments = useMemo(() => Array.from(new Set([...pairs.map((pair) => pair.symbol), 'XAU/USD'])), [pairs]); const filtered = instruments.filter((item) => item.toLowerCase().includes(query.trim().toLowerCase())); const compactMobile = view !== 'market'
  const currentMode = typeof window !== 'undefined' && sessionStorage.getItem('shafx-trading-mode') === 'broker' ? 'broker' : 'simulator'
  const switchMode = (mode: 'simulator' | 'broker') => { sessionStorage.setItem('shafx-trading-mode', mode); window.location.assign(`/?account=${mode === 'broker' ? 'broker' : 'demo'}`) }
  return <header className="sticky top-0 z-40 border-b border-shafx-border bg-shafx-surface shadow-sm"><div className="flex min-h-14 items-center gap-2 px-2 sm:gap-3 sm:px-4">
    <div className="flex flex-shrink-0 items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-shafx-primary"><Activity className="h-5 w-5 text-white" /></div><span className="hidden text-lg font-bold tracking-tight sm:block">SHAFX</span></div>
    {compactMobile ? <div className="flex min-w-0 flex-1 items-center justify-between gap-2"><div><div className="text-sm font-semibold">{viewTitles[view]}</div><div className="text-[10px] text-shafx-textMuted">{currentMode === 'broker' ? 'Broker account' : 'Demo simulator'}</div></div><span className="rounded border border-shafx-primary/20 bg-shafx-primary/10 px-2 py-1 text-[10px] text-shafx-primary">{currentMode === 'broker' ? 'BROKER' : 'DEMO'}</span></div> : <>
      <div className="relative min-w-0 flex-1 md:flex-none"><button type="button" onClick={() => setMarketOpen((open) => !open)} className="flex min-h-11 w-full min-w-0 items-center gap-2 rounded-md border border-shafx-border bg-shafx-bg px-2.5 text-left hover:bg-shafx-surfaceHover md:w-52" aria-expanded={marketOpen} aria-label="Choose trading instrument"><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{symbol}</div><div className="hidden text-[10px] text-shafx-textMuted sm:block">Market • {formatPrice(price, pricePrecision)}</div></div><ChevronDown className={`h-4 w-4 flex-shrink-0 text-shafx-textMuted transition-transform ${marketOpen ? 'rotate-180' : ''}`} /></button>{marketOpen && <div className="absolute left-0 top-[calc(100%+6px)] z-50 w-[min(92vw,320px)] rounded-lg border border-shafx-border bg-shafx-surface p-2 shadow-2xl"><div className="mb-2 flex items-center gap-2 rounded border border-shafx-border bg-shafx-bg px-2.5"><Search className="h-4 w-4 text-shafx-textMuted" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search EUR/USD, gold..." className="h-10 w-full bg-transparent text-sm outline-none placeholder:text-shafx-textMuted" /></div><div className="mb-1 px-2 text-[10px] font-semibold uppercase tracking-wider text-shafx-textMuted">Markets</div><div className="max-h-64 overflow-y-auto">{filtered.map((item) => <button key={item} type="button" onClick={() => { onSelectPair(item); setMarketOpen(false); setQuery('') }} className={`flex min-h-11 w-full items-center justify-between rounded px-2.5 text-left text-sm hover:bg-shafx-surfaceHover ${item === symbol ? 'bg-shafx-primary/10 text-shafx-primary' : ''}`}><span>{item}</span><span className="text-[10px] text-shafx-textMuted">{item === 'XAU/USD' ? 'Gold' : 'Forex'}</span></button>)}{filtered.length === 0 && <div className="px-2.5 py-4 text-center text-xs text-shafx-textMuted">No matching instrument</div>}</div></div>}</div>
      <div className="hidden items-center gap-2 border-l border-shafx-border pl-3 lg:flex"><div className="font-mono text-base font-semibold tabular">{formatPrice(price, pricePrecision)}</div><span className="flex items-center gap-1 text-[10px] text-shafx-success"><Wifi className="h-3 w-3" />Simulated</span></div>
      <div className="ml-auto flex min-w-0 items-center gap-1.5"><div className="relative"><button type="button" onClick={() => setAccountOpen((open) => !open)} className="flex min-h-11 items-center gap-1.5 rounded-md border border-shafx-border bg-shafx-bg px-2" aria-expanded={accountOpen} aria-label="Change trading account"><span className="h-2 w-2 rounded-full bg-shafx-success" /><span className="text-[11px] font-semibold">{currentMode === 'broker' ? 'Broker' : 'Demo'}</span><ChevronDown className="h-3.5 w-3.5 text-shafx-textMuted" /></button>{accountOpen && <div className="absolute right-0 top-[calc(100%+6px)] z-50 w-60 rounded-lg border border-shafx-border bg-shafx-surface p-1.5 shadow-2xl"><div className="px-3 py-2 text-[9px] font-semibold uppercase tracking-wider text-shafx-textMuted">Trading account</div><button type="button" onClick={() => { setAccountOpen(false); if (currentMode !== 'simulator') switchMode('simulator') }} className={`flex min-h-11 w-full items-center justify-between rounded px-3 text-left text-sm ${currentMode === 'simulator' ? 'bg-shafx-primary/10' : 'hover:bg-shafx-surfaceHover'}`}><span>Demo account</span><span className="text-[10px] text-shafx-primary">{currentMode === 'simulator' ? 'ACTIVE' : 'SWITCH'}</span></button><button type="button" onClick={() => { setAccountOpen(false); if (currentMode !== 'broker') switchMode('broker') }} className={`mt-1 flex min-h-11 w-full items-center justify-between rounded px-3 text-left text-sm ${currentMode === 'broker' ? 'bg-shafx-primary/10' : 'hover:bg-shafx-surfaceHover'}`}><span>Real / broker account</span><span className="text-[10px] text-shafx-primary">{currentMode === 'broker' ? 'ACTIVE' : 'SWITCH'}</span></button><p className="px-3 py-2 text-[10px] leading-relaxed text-shafx-textMuted">Switching is immediate. Choosing Broker takes you to the broker connection screen first.</p></div>}</div><div className="hidden sm:block"><DerivAccountControl /></div><div className="flex max-w-[43vw] items-center gap-0.5 overflow-x-auto rounded-md border border-shafx-border bg-shafx-bg p-1 sm:max-w-none sm:gap-1">{TIMEFRAMES.map((tf) => <button key={tf} type="button" onClick={() => onTimeframeChange(tf)} aria-pressed={timeframe === tf} className={`min-h-10 flex-shrink-0 rounded px-2 text-[10px] font-medium transition-colors sm:px-3 sm:text-[11px] ${timeframe === tf ? 'bg-shafx-primary text-white' : 'text-shafx-textMuted hover:bg-shafx-surfaceHover hover:text-shafx-text'}`}>{tf}</button>)}</div></div>
    </>}
  </div></header>
}
