import React, { useState } from 'react'
import { ArrowLeft, ArrowRight, BarChart3, CheckCircle2, ChevronRight, Link2, ShieldCheck, WalletCards } from 'lucide-react'
import { PublicWelcome } from './PublicWelcome'
import { ProviderConnectionControl } from '../market/ProviderConnectionControl'
import { providerCatalog } from '../../integrations/catalog'
import { useAuth } from '../../app/AuthContext'
import { setStoredTradingMode, type TradingMode } from '../../app/tradingMode'

interface Props { onEnterTerminal: (mode: TradingMode) => void }

export const AccountAccessGate: React.FC<Props> = ({ onEnterTerminal }) => {
  const { user, loading } = useAuth()
  const [mode, setMode] = useState<TradingMode | null>(() => {
    if (typeof window === 'undefined') return null
    const requested = new URLSearchParams(window.location.search).get('account')
    return requested === 'broker' ? 'broker' : requested === 'demo' ? 'simulator' : null
  })
  const enter = (nextMode: TradingMode) => { setStoredTradingMode(nextMode, user?.simulatorAccountId); onEnterTerminal(nextMode) }

  if (loading) return <div className="flex min-h-[calc(100vh-28px)] items-center justify-center bg-shafx-bg px-4 text-shafx-text"><div className="rounded-2xl border border-shafx-border bg-shafx-surface px-7 py-6 text-center shafx-glow"><div className="text-sm font-semibold">Preparing your workspace</div><div className="mt-1 text-[11px] text-shafx-textMuted">Checking the SHAFX session…</div></div></div>
  if (!user) return <PublicWelcome />

  if (!mode) return <main className="min-h-[calc(100vh-28px)] overflow-y-auto bg-shafx-bg px-4 py-7 text-shafx-text sm:px-8 sm:py-10"><div className="mx-auto max-w-6xl">
    <header className="flex items-center justify-between"><div><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-shafx-accent/30 bg-shafx-accent/10 text-shafx-accent"><BarChart3 className="h-5 w-5" /></div><div><div className="text-lg font-semibold">SHAFX</div><div className="text-[9px] uppercase tracking-[0.22em] text-shafx-textMuted">Workspace selector</div></div></div></div><div className="hidden items-center gap-2 text-[10px] text-shafx-textMuted sm:flex"><span className="rounded-full border border-shafx-border px-2.5 py-1">Signed in</span><span>{user.displayName || user.email.split('@')[0]}</span></div></header>
    <div className="mx-auto mt-16 max-w-4xl"><div className="text-center"><div className="text-[10px] font-semibold uppercase tracking-[0.24em] text-shafx-textMuted">Choose your environment</div><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">Start where you are.</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-shafx-textMuted">The SHAFX workspace remains the same. Only the market and account source changes.</p></div>
      <div className="mt-9 grid gap-4 md:grid-cols-2">
        <button type="button" onClick={() => setMode('simulator')} className="group rounded-3xl border border-shafx-border bg-shafx-surface p-6 text-left transition hover:-translate-y-0.5 hover:border-shafx-accent/40 shafx-glow"><div className="flex items-center justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-shafx-accent/10 text-shafx-accent"><BarChart3 className="h-6 w-6" /></div><ArrowRight className="h-5 w-5 text-shafx-textMuted transition group-hover:text-shafx-text" /></div><div className="mt-7 text-lg font-semibold">SHAFX Simulator</div><p className="mt-2 max-w-md text-xs leading-6 text-shafx-textMuted">Practice market structure, risk, replay and strategy ideas with simulated funds. No broker connection required.</p><div className="mt-6 flex flex-wrap gap-2 text-[9px] text-shafx-textMuted"><span className="rounded-full border border-shafx-border px-2.5 py-1">Replay</span><span className="rounded-full border border-shafx-border px-2.5 py-1">Backtest</span><span className="rounded-full border border-shafx-border px-2.5 py-1">SHAFX Bot</span></div></button>
        <button type="button" onClick={() => setMode('broker')} className="group rounded-3xl border border-shafx-accent/30 bg-[linear-gradient(145deg,rgba(124,92,252,.10),rgba(13,18,26,.96)_50%)] p-6 text-left transition hover:-translate-y-0.5 hover:border-shafx-accent/50 shafx-glow"><div className="flex items-center justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-shafx-success/10 text-shafx-success"><WalletCards className="h-6 w-6" /></div><ArrowRight className="h-5 w-5 text-shafx-textMuted transition group-hover:text-shafx-text" /></div><div className="mt-7 text-lg font-semibold">Connect a provider</div><p className="mt-2 max-w-md text-xs leading-6 text-shafx-textMuted">Connect a supported broker or exchange and let SHAFX adapt its account, symbols and available execution capabilities.</p><div className="mt-6 flex flex-wrap gap-2 text-[9px] text-shafx-textMuted"><span className="rounded-full border border-shafx-border px-2.5 py-1">Adaptive UI</span><span className="rounded-full border border-shafx-border px-2.5 py-1">Normalized data</span><span className="rounded-full border border-shafx-border px-2.5 py-1">Safety gates</span></div></button>
      </div>
      <div className="mt-5 flex items-center justify-center gap-2 text-[10px] text-shafx-textMuted"><CheckCircle2 className="h-3.5 w-3.5 text-shafx-success" />Your SHAFX identity stays separate from connected provider credentials.</div>
    </div>
  </div></main>

  if (mode === 'broker') return <main className="min-h-[calc(100vh-28px)] overflow-y-auto bg-shafx-bg px-4 py-7 text-shafx-text sm:px-8 sm:py-10"><div className="mx-auto max-w-6xl">
    <button type="button" onClick={() => setMode(null)} className="flex items-center gap-2 text-[11px] text-shafx-textMuted hover:text-shafx-text"><ArrowLeft className="h-3.5 w-3.5" />Workspace selector</button>
    <header className="mt-7 flex flex-col justify-between gap-4 border-b border-shafx-border pb-6 sm:flex-row sm:items-end"><div><div className="text-[10px] font-semibold uppercase tracking-[0.22em] text-shafx-textMuted">Provider connections</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Connect your market source.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-shafx-textMuted">One SHAFX interface, multiple adapters. The selected provider changes the data source and the actions available in the workspace — not the whole product.</p></div><div className="flex items-center gap-2 rounded-full border border-shafx-border bg-shafx-surface px-3 py-2 text-[10px] text-shafx-textMuted"><ShieldCheck className="h-3.5 w-3.5 text-shafx-success" />Server-side credential boundary</div></header>
    <section className="mt-6 rounded-3xl border border-shafx-accent/25 bg-shafx-surface p-5 shafx-glow"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-sm font-semibold"><Link2 className="h-4 w-4 text-shafx-accent" />Connection manager</div><p className="mt-1 text-[11px] text-shafx-textMuted">Use the provider adapter that matches your account. Additional adapters can be added without rebuilding the terminal shell.</p></div><ProviderConnectionControl /></div></section>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{providerCatalog.filter((item) => item.id !== 'simulator').map((provider) => <div key={provider.id} className="rounded-2xl border border-shafx-border bg-shafx-surface/80 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-semibold">{provider.name}</div><p className="mt-1 text-[10px] leading-5 text-shafx-textMuted">{provider.description}</p></div><span className={`rounded-full border px-2 py-1 text-[8px] font-semibold tracking-wide ${provider.status === 'available' ? 'border-shafx-success/25 bg-shafx-success/5 text-shafx-success' : 'border-shafx-border text-shafx-textMuted'}`}>{provider.status === 'available' ? 'AVAILABLE' : 'PLANNED'}</span></div><div className="mt-4 flex items-center gap-2 text-[9px] text-shafx-textMuted"><span>Execution: {provider.capabilities.orderPlacement ? 'adapter present' : 'read / market'}</span><ChevronRight className="h-3 w-3" /></div></div>)}</section>
    <div className="mt-5 rounded-2xl border border-shafx-border bg-shafx-surface/60 p-4 text-[10px] leading-5 text-shafx-textMuted"><strong className="text-shafx-warning">Release note:</strong> connecting a provider does not by itself authorize a real-money order. External execution remains explicitly gated in the server release boundary.</div>
    <button type="button" onClick={() => enter('broker')} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl border border-shafx-accent/30 bg-shafx-accent/10 text-sm font-semibold text-shafx-accent hover:bg-shafx-accent/15">Open adaptive workspace <ArrowRight className="h-4 w-4" /></button>
  </div></main>

  return <main className="min-h-[calc(100vh-28px)] overflow-y-auto bg-shafx-bg px-4 py-10 text-shafx-text sm:px-8"><div className="mx-auto max-w-3xl text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl border border-shafx-accent/30 bg-shafx-accent/10 text-shafx-accent"><BarChart3 className="h-6 w-6" /></div><div className="mt-5 text-[10px] font-semibold uppercase tracking-[0.22em] text-shafx-textMuted">Simulator selected</div><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Your private market lab is ready.</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-shafx-textMuted">Practice with simulated funds, review market structure, backtest ideas and use the SHAFX Bot without connecting a broker.</p><div className="mx-auto mt-7 max-w-xl rounded-3xl border border-shafx-border bg-shafx-surface p-5 text-left shafx-glow"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-shafx-accent/10 text-shafx-accent"><WalletCards className="h-5 w-5" /></div><div><div className="text-sm font-semibold">Simulator account</div><div className="mt-1 font-mono text-[10px] text-shafx-textMuted">{user.simulatorAccountId}</div></div></div><div className="mt-4 flex items-center gap-2 text-[10px] text-shafx-textMuted"><ShieldCheck className="h-3.5 w-3.5 text-shafx-success" />No broker credentials are required.</div></div><button type="button" onClick={() => enter('simulator')} className="mx-auto mt-4 flex min-h-12 w-full max-w-xl items-center justify-center gap-2 rounded-2xl bg-shafx-accent text-sm font-semibold text-white shadow-lg shadow-shafx-accent/15 hover:bg-shafx-primaryHover">Enter SHAFX workspace <ArrowRight className="h-4 w-4" /></button><button type="button" onClick={() => setMode(null)} className="mt-2 py-2 text-[10px] text-shafx-textMuted hover:text-shafx-text">Choose another environment</button></div></main>
}
