import React, { useState } from 'react'
import { ArrowRight, BarChart3, CheckCircle2, ShieldCheck, WalletCards } from 'lucide-react'
import { PublicWelcome } from './PublicWelcome'
import { DerivAccountControl } from '../market/DerivAccountControl'
import { useAuth } from '../../app/AuthContext'
import { setStoredTradingMode, type TradingMode } from '../../app/tradingMode'

interface Props { onEnterTerminal: (mode: TradingMode) => void }

export const AccountAccessGate: React.FC<Props> = ({ onEnterTerminal }) => {
  const { user, loading } = useAuth()
  const [mode, setMode] = useState<TradingMode | null>(() => {
    if (typeof window === 'undefined') return null
    const requested = new URLSearchParams(window.location.search).get('account')
    return requested === 'broker' ? 'broker' : requested === 'demo' ? 'simulator' : null
  })
  const enter = (nextMode: TradingMode) => { setStoredTradingMode(nextMode, user?.simulatorAccountId); onEnterTerminal(nextMode) }

  if (loading) return <div className="flex min-h-[calc(100vh-32px)] items-center justify-center bg-shafx-bg px-4 text-shafx-text"><div className="rounded-2xl border border-shafx-border bg-shafx-surface px-6 py-5 text-center shadow-xl"><div className="text-sm font-semibold">Checking your SHAFX account…</div><div className="mt-1 text-[11px] text-shafx-textMuted">Please wait.</div></div></div>
  if (!user) return <PublicWelcome />

  if (!mode) return <div className="min-h-[calc(100vh-32px)] overflow-y-auto bg-shafx-bg px-4 py-8 text-shafx-text sm:px-6"><div className="mx-auto max-w-2xl"><div className="text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl border border-shafx-primary/30 bg-shafx-primary/10 text-shafx-primary"><CheckCircle2 className="h-6 w-6" /></div><div className="mt-4 text-[10px] uppercase tracking-[0.22em] text-shafx-textMuted">Account ready</div><h1 className="mt-1 text-2xl font-bold">Choose how you want to use SHAFX</h1><p className="mx-auto mt-2 max-w-xl text-sm text-shafx-textMuted">Welcome, {user.displayName || user.email.split('@')[0]}. Choose a simulator account or connect an existing broker account.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setMode('simulator')} className="group rounded-2xl border border-shafx-border bg-shafx-surface p-5 text-left transition hover:border-shafx-primary"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-shafx-primary/10 text-shafx-primary"><BarChart3 className="h-5 w-5" /></div><ArrowRight className="h-4 w-4 text-shafx-textMuted" /></div><div className="mt-5 text-base font-semibold">Demo account</div><p className="mt-1 text-xs leading-relaxed text-shafx-textMuted">Practice inside the SHAFX simulator. No broker account is required.</p><div className="mt-4 text-[10px] font-semibold text-shafx-primary">ENTER SIMULATOR</div></button><button type="button" onClick={() => setMode('broker')} className="group rounded-2xl border border-shafx-border bg-shafx-surface p-5 text-left transition hover:border-shafx-primary"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-shafx-primary/10 text-shafx-primary"><WalletCards className="h-5 w-5" /></div><ArrowRight className="h-4 w-4 text-shafx-textMuted" /></div><div className="mt-5 text-base font-semibold">Real / broker account</div><p className="mt-1 text-xs leading-relaxed text-shafx-textMuted">Connect an existing broker account. SHAFX does not create the broker account for you.</p><div className="mt-4 text-[10px] font-semibold text-shafx-primary">CONNECT A BROKER</div></button></div><div className="mt-5 rounded-xl border border-shafx-border bg-shafx-surface p-4 text-center text-[10px] text-shafx-textMuted"><ShieldCheck className="mx-auto mb-2 h-4 w-4 text-shafx-primary" />Your SHAFX account and broker account stay separate.</div></div></div>
  if (mode === 'broker') return <div className="min-h-[calc(100vh-32px)] overflow-y-auto bg-shafx-bg px-4 py-8 text-shafx-text sm:px-6"><div className="mx-auto max-w-2xl"><button type="button" onClick={() => setMode(null)} className="text-[11px] text-shafx-textMuted hover:text-shafx-text">← Back to account choice</button><div className="mt-6"><div className="text-[10px] uppercase tracking-[0.22em] text-shafx-textMuted">Real / broker account</div><h1 className="mt-1 text-2xl font-bold">Connect your broker</h1><p className="mt-2 text-sm text-shafx-textMuted">Choose a supported broker where you already have an account. SHAFX keeps your broker credentials outside the SHAFX account.</p></div><div className="mt-6 space-y-3"><div className="flex flex-col gap-4 rounded-2xl border border-shafx-primary/30 bg-shafx-surface p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-base font-semibold">Deriv</div><div className="mt-1 text-xs text-shafx-textMuted">OAuth connection is available now.</div></div><DerivAccountControl /></div><div className="flex items-center justify-between rounded-2xl border border-shafx-border bg-shafx-surface p-5"><div><div className="text-base font-semibold">HFM</div><div className="mt-1 text-xs text-shafx-textMuted">Broker integration planned; API access requires broker support/approval.</div></div><span className="rounded-full border border-shafx-border px-2.5 py-1 text-[9px] text-shafx-textMuted">COMING SOON</span></div><div className="flex items-center justify-between rounded-2xl border border-shafx-border bg-shafx-surface p-5"><div><div className="text-base font-semibold">More brokers</div><div className="mt-1 text-xs text-shafx-textMuted">SHAFX is being built with a multi-broker connection layer.</div></div><span className="rounded-full border border-shafx-border px-2.5 py-1 text-[9px] text-shafx-textMuted">EXPANDING</span></div></div><div className="mt-5 rounded-xl border border-yellow-500/20 bg-yellow-500/5 p-4 text-[10px] leading-relaxed text-shafx-textMuted"><strong className="text-yellow-400">Important:</strong> connecting a broker does not by itself place a real-money order. SHAFX real-money execution remains disabled until the broker execution layer is explicitly enabled and tested.</div><button type="button" onClick={() => enter('broker')} className="mt-5 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-shafx-border bg-shafx-surface text-xs font-semibold hover:border-shafx-primary">Continue to SHAFX <ArrowRight className="h-4 w-4" /></button></div></div>
  return <div className="min-h-[calc(100vh-32px)] overflow-y-auto bg-shafx-bg px-4 py-8 text-shafx-text sm:px-6"><div className="mx-auto max-w-2xl"><div className="text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl border border-shafx-primary/30 bg-shafx-primary/10 text-shafx-primary"><BarChart3 className="h-6 w-6" /></div><div className="mt-4 text-[10px] uppercase tracking-[0.22em] text-shafx-textMuted">Demo account selected</div><h1 className="mt-1 text-2xl font-bold">Your SHAFX simulator is ready</h1><p className="mx-auto mt-2 max-w-xl text-sm text-shafx-textMuted">You can now enter the terminal and practice with simulated funds. No broker connection is required.</p></div><div className="mt-6 rounded-2xl border border-shafx-border bg-shafx-surface p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-shafx-primary/10 text-shafx-primary"><WalletCards className="h-5 w-5" /></div><div><div className="text-sm font-semibold">SHAFX Simulator</div><div className="text-[11px] text-shafx-textMuted">Your simulator account: {user.simulatorAccountId}</div></div></div></div><button type="button" onClick={() => enter('simulator')} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-shafx-primary text-sm font-semibold text-white">Enter SHAFX Simulator <ArrowRight className="h-4 w-4" /></button><button type="button" onClick={() => setMode(null)} className="mt-2 w-full py-2 text-[10px] text-shafx-textMuted">Choose another account type</button></div></div>
}
