import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'

export type BotPlan = 'FREE' | 'REGULAR' | 'PRO'
export interface ShafxUser { id: string; email: string; displayName: string | null; status: 'active' | 'suspended' | 'banned'; simulatorAccountId: string; createdAt: string; botPlan: BotPlan }
interface AuthContextValue { user: ShafxUser | null; loading: boolean; error: string | null; signUp: (input: { displayName: string; email: string; password: string; website?: string }) => Promise<{ needsEmailConfirmation?: boolean; message?: string }>; signIn: (input: { email: string; password: string }) => Promise<{ requiresVerification?: boolean; email?: string; message?: string }>; requestLoginCode: (email: string) => Promise<{ message?: string }>; verifyEmailCode: (input: { email: string; code: string; purpose: 'signup' | 'login' }) => Promise<void>; signOut: () => Promise<void>; refresh: () => Promise<void> }
const AuthContext = createContext<AuthContextValue | null>(null)
const syncSimulatorIdentity = (user: ShafxUser | null): void => { if (typeof window === 'undefined') return; if (user?.simulatorAccountId) window.sessionStorage.setItem('shafx-simulator-account-id', user.simulatorAccountId); else window.sessionStorage.removeItem('shafx-simulator-account-id') }
async function request(action: string, options: RequestInit = {}) { const response = await fetch(`/api/auth?action=${encodeURIComponent(action)}`, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const data = await response.json().catch(() => ({ ok: false, error: 'Unexpected SHAFX identity response.' })); if (!response.ok || !data.ok) throw new Error(data.error || 'SHAFX identity request failed.'); return data }
export const AuthProvider: React.FC<React.PropsWithChildren> = ({ children }) => { const [user, setUser] = useState<ShafxUser | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const refresh = useCallback(async () => { setLoading(true); try { const data = await request('me'); setUser(data.user); syncSimulatorIdentity(data.user); setError(null) } catch (err) { setUser(null); syncSimulatorIdentity(null); setError(err instanceof Error && err.message !== 'Not signed in' ? err.message : null) } finally { setLoading(false) } }, []); useEffect(() => { void refresh() }, [refresh]); const signUp = useCallback(async (input: { displayName: string; email: string; password: string; website?: string }) => { const data = await request('signup', { method: 'POST', body: JSON.stringify(input) }); if (data.user) { setUser(data.user); syncSimulatorIdentity(data.user) } return { needsEmailConfirmation: data.needsEmailConfirmation, message: data.message } }, []); const signIn = useCallback(async (input: { email: string; password: string }) => { const data = await request('login', { method: 'POST', body: JSON.stringify(input) }); if (data.user) { setUser(data.user); syncSimulatorIdentity(data.user) } setError(null); return { requiresVerification: data.requiresVerification, email: data.email, message: data.message } }, [])
  const requestLoginCode = useCallback(async (email: string) => request('request-login-code', { method: 'POST', body: JSON.stringify({ email }) }), [])
  const verifyEmailCode = useCallback(async (input: { email: string; code: string; purpose: 'signup' | 'login' }) => { const action = input.purpose === 'signup' ? 'verify-email-code' : 'verify-login-code'; const data = await request(action, { method: 'POST', body: JSON.stringify({ email: input.email, code: input.code }) }); setUser(data.user); syncSimulatorIdentity(data.user); setError(null) }, []); const signOut = useCallback(async () => { await request('logout'); setUser(null); syncSimulatorIdentity(null); setError(null) }, []); const value = useMemo(() => ({ user, loading, error, signUp, signIn, requestLoginCode, verifyEmailCode, signOut, refresh }), [user, loading, error, signUp, signIn, requestLoginCode, verifyEmailCode, signOut, refresh]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider> }
export const useAuth = (): AuthContextValue => { const context = useContext(AuthContext); if (!context) throw new Error('useAuth must be used inside AuthProvider'); return context }
