import type { ProviderDescriptor } from '../core/types'

export const BINANCE_PROVIDER_DESCRIPTOR: ProviderDescriptor = {
  id: 'binance',
  name: 'Binance',
  kind: 'exchange',
  status: 'available',
  executionMode: 'external',
  authMethods: ['api_key'],
  description: 'Read-only Binance Spot account and market-data adapter. SHAFX does not place real Binance orders.',
  credentialFields: [
    { key: 'apiKey', label: 'API Key', type: 'text', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'secret', required: true },
    { key: 'environment', label: 'Environment', type: 'select', required: true, options: [{ value: 'demo', label: 'Spot Testnet / Demo' }, { value: 'live', label: 'Live' }] },
    { key: 'label', label: 'Connection label', type: 'text', required: false },
  ],
  rateLimit: { requestsPerSecond: 10, scope: 'connection' },
  capabilities: {
    accountRead: true,
    marketData: true,
    historicalCandles: true,
    realtimeMarketData: true,
    realtimeAccountData: false,
    positionsRead: false,
    ordersRead: true,
    orderPlacement: false,
    orderCancellation: false,
    orderModification: false,
    orderLookupByClientOrderId: false,
    positionClose: false,
    multipleAccounts: false,
    demoAccounts: true,
    symbolMetadata: true,
    funding: { deposit: 'unsupported', withdrawal: 'unsupported' },
  },
}