import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { ChevronDown } from 'lucide-react'
import { TerminalProvider, useTerminal } from './app/TerminalContext'
import { ErrorBoundary } from './app/ErrorBoundary'
import { useAuth } from './app/AuthContext'
import { TopNav } from './components/layout/TopNav'
import { MobileNav, type MobileNavTab } from './components/layout/MobileNav'
import { DerivLiveControl } from './components/market/DerivLiveControl'
import { CandlestickChart } from './components/chart/CandlestickChart'
import { analyzeCurrentSetup, buildAIChartAnnotations } from './components/chart/buildAIChartAnnotations'
import { Watchlist } from './components/watchlist/Watchlist'
import { MarketAnalysisPanel } from './components/analysis/MarketAnalysis'
import { AIAssistantPanel } from './components/ai/AIAssistantPanel'
import { TradingAgentPanel } from './components/ai/TradingAgentPanel'
import { BacktestPanel } from './components/backtest/BacktestPanel'
import { ReplayPanel } from './components/backtest/ReplayPanel'
import { PerformancePanel } from './components/performance/PerformancePanel'
import { TradingJournalPanel } from './components/performance/TradingJournalPanel'
import { OrderPanel } from './components/order/OrderPanel'
import { AccountPanel } from './components/account/AccountPanel'
import { TradesPanel } from './components/trades/TradesPanel'
import { Toast, type ToastMessage } from './components/common/Toast'
import { marketDataSource } from './data/createMarketDataSource'
import { getConversionRate } from './data/mock/symbols'
import { applyDemoProfit, setDemoOpenPositions, setDemoTradeHistory } from './engine/simulator/accountStore'
import { submitSimulatedOrder } from './engine/simulator/submitSimulatedOrder'
import { closeSimulatedPosition, markSimulatedPosition } from './engine/simulator/positionManager'
import type { AccountData, AIAnalysis, MarketAnalysis, MarketPair, OHLCV, SimulatedOrderDraft, SymbolSpec, TradeOrder } from './types'

const isBrokerMode = (): boolean => typeof window !== 'undefined' && window.sessionStorage.getItem('shafx-trading-mode') === 'broker'
const isSimulatorMode = (): boolean => !isBrokerMode()

const TerminalContent: React.FC = () => {
  const { selectedSymbol, setSelectedSymbol, timeframe, setTimeframe } = useTerminal()
  const { user } = useAuth()
  const [currentPrice, setCurrentPrice] = useState(1.08542)
  const [candles, setCandles] = useState<OHLCV[]>([])
  const [liveCandles, setLiveCandles] = useState<OHLCV[]>([])
  const [liveMarketActive, setLiveMarketActive] = useState(false)
  const [replayCount, setReplayCount] = useState(0)
  const [mobileTab, setMobileTab] = useState<MobileNavTab>('market')
  const [manualTradeOpen, setManualTradeOpen] = useState(false)
  const [accountData, setAccountData] = useState<AccountData | null>(null)
  const [symbolSpec, setSymbolSpec] = useState<SymbolSpec | null>(null)
  const [watchlist, setWatchlist] = useState<MarketPair[]>([])
  const [marketAnalysis, setMarketAnalysis] = useState<MarketAnalysis | null>(null)
  const [aiAnalysis, setAiAnalysis] = useState<AIAnalysis | null>(null)
  const [openPositions, setOpenPositions] = useState<TradeOrder[]>([])
  const [pendingOrders, setPendingOrders] = useState<TradeOrder[]>([])
  const [tradeHistory, setTradeHistory] = useState<TradeOrder[]>([])
  const [toast, setToast] = useState<ToastMessage | null>(null)
  const accountInitialized = useRef(false)
  const simulatorInitialized = useRef(false)
  const symbolSpecCache = useRef<Record<string, SymbolSpec>>({})
  const toastId = useRef(0)
  const pushToast = useCallback((text: string) => { toastId.current += 1; setToast({ id: toastId.current, text }) }, [])

  useEffect(() => { let cancelled = false; const load = async (): Promise<void> => { try { const [wl, acc, spec, cands, ma, ai, positions, pending, history] = await Promise.all([marketDataSource.getWatchlist(), marketDataSource.getAccountData(), marketDataSource.getSymbolSpec(selectedSymbol), marketDataSource.getCandles(selectedSymbol, timeframe), marketDataSource.getMarketAnalysis(selectedSymbol), marketDataSource.getAIAnalysis(selectedSymbol), marketDataSource.getOpenPositions(), marketDataSource.getPendingOrders(), marketDataSource.getTradeHistory()]); if (cancelled) return; symbolSpecCache.current[selectedSymbol] = spec; setWatchlist(wl); setSymbolSpec(spec); setCandles(cands); setLiveCandles([]); setReplayCount(cands.length); setMarketAnalysis(ma); setAiAnalysis(ai); if (!accountInitialized.current) { accountInitialized.current = true; setAccountData(acc) }; if (!simulatorInitialized.current) { simulatorInitialized.current = true; setOpenPositions(positions); setPendingOrders(pending); setTradeHistory(history) }; const pair = wl.find((p) => p.symbol === selectedSymbol); if (pair) setCurrentPrice(pair.price) } catch (err) { if (!cancelled) pushToast(err instanceof Error ? err.message : 'Unable to load market data.') } }; void load(); return () => { cancelled = true } }, [pushToast, selectedSymbol, timeframe])
  useEffect(() => { if (!accountData || !isBrokerMode()) return; let cancelled = false; const refreshBrokerBalance = async (): Promise<void> => { try { const next = await marketDataSource.getAccountData(); if (cancelled) return; setAccountData((prev) => { if (!prev) return next; const equity = Number((next.balance + prev.floatingPL).toFixed(2)); const freeMargin = Number((equity - next.usedMargin).toFixed(2)); if (prev.balance === next.balance && prev.currency === next.currency && prev.equity === equity && prev.freeMargin === freeMargin) return prev; return { ...prev, balance: next.balance, currency: next.currency, usedMargin: next.usedMargin, equity, freeMargin } }) } catch {} }; const timer = window.setInterval(() => { void refreshBrokerBalance() }, 5000); return () => { cancelled = true; window.clearInterval(timer) } }, [accountData?.currency])
  useEffect(() => { if (!isSimulatorMode()) return; setDemoOpenPositions(openPositions); setDemoTradeHistory(tradeHistory) }, [openPositions, tradeHistory])
  const visibleCandles = useMemo(() => replayCount > 0 && replayCount < candles.length ? candles.slice(0, replayCount) : candles, [candles, replayCount])
  const chartCandles = liveMarketActive && liveCandles.length > 0 ? liveCandles : visibleCandles
  const replayActive = !liveMarketActive && visibleCandles.length > 0 && visibleCandles.length < candles.length
  const displayPrice = liveMarketActive && liveCandles.length > 0 ? (liveCandles[liveCandles.length - 1]?.close ?? currentPrice) : replayActive ? (visibleCandles[visibleCandles.length - 1]?.close ?? currentPrice) : currentPrice
  const conversionRate = symbolSpec ? getConversionRate(symbolSpec.quoteCurrency, accountData?.currency ?? 'USD') : undefined
  const chartAnnotations = useMemo(() => buildAIChartAnnotations(selectedSymbol, chartCandles), [selectedSymbol, chartCandles])
  const aiSetup = useMemo(() => analyzeCurrentSetup(selectedSymbol, chartCandles)?.preferredSetup ?? null, [selectedSymbol, chartCandles])
  const reviewAISetup = useCallback((): void => { setMobileTab('market'); setManualTradeOpen(true); window.setTimeout(() => document.getElementById('manual-trade')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 60) }, [])
  const handleLiveUpdate = useCallback((nextCandles: OHLCV[], price: number): void => { setLiveCandles(nextCandles); setCurrentPrice(price) }, [])
  const handleLiveActiveChange = useCallback((active: boolean): void => { setLiveMarketActive(active); if (!active) setLiveCandles([]) }, [])
  const handleOrderSubmit = useCallback((draft: SimulatedOrderDraft): void => { try { const order = submitSimulatedOrder(draft); setOpenPositions((prev) => [...prev, order]); pushToast(`Simulated ${order.type} ${order.lotSize.toFixed(2)} lots ${order.symbol} placed (${order.id}).`) } catch (err) { pushToast(err instanceof Error ? err.message : 'Unable to place simulated order.') } }, [pushToast])
  const handleBotOrder = useCallback((order: TradeOrder): void => { setOpenPositions((prev) => prev.some((item) => item.id === order.id) ? prev : [...prev, order]); pushToast(`SHAFX Bot opened simulated ${order.type} ${order.symbol} at ${order.entryPrice}. SL ${order.stopLoss ?? '—'} • TP ${order.takeProfit ?? '—'}.`) }, [pushToast])
  const handleClosePosition = useCallback(async (id: string): Promise<void> => { const order = openPositions.find((item) => item.id === id); if (!order || !accountData) return; try { const [spec, wl] = await Promise.all([marketDataSource.getSymbolSpec(order.symbol), marketDataSource.getWatchlist()]); const pair = wl.find((item) => item.symbol === order.symbol); const exitPrice = order.symbol === selectedSymbol ? displayPrice : pair?.price; if (!exitPrice) throw new Error('No simulated market price is available for this position.'); const rate = getConversionRate(spec.quoteCurrency, accountData.currency); const closed = closeSimulatedPosition(order, { exitPrice, conversionRate: rate }, spec); const realized = closed.profit ?? 0; if (isSimulatorMode()) applyDemoProfit(realized); setOpenPositions((prev) => prev.filter((item) => item.id !== id)); setTradeHistory((prev) => [closed, ...prev]); setAccountData((prev) => { if (!prev) return prev; const balance = Number((prev.balance + realized).toFixed(2)); const floatingPL = openPositions.filter((item) => item.id !== id && item.status === 'open').reduce((sum, item) => sum + (item.profit ?? 0), 0); const equity = Number((balance + floatingPL).toFixed(2)); return { ...prev, balance, equity, floatingPL, freeMargin: Number((equity - prev.usedMargin).toFixed(2)) } }); pushToast(`Simulated ${closed.type} ${closed.symbol} closed at ${exitPrice.toFixed(spec.pricePrecision)} (${closed.profit !== undefined && closed.profit >= 0 ? '+' : ''}${closed.profit?.toFixed(2)} ${accountData.currency}).`) } catch (err) { pushToast(err instanceof Error ? err.message : 'Unable to close simulated position.') } }, [accountData, displayPrice, openPositions, pushToast, selectedSymbol])
  useEffect(() => { if (!accountData || openPositions.length === 0) return; let cancelled = false; const refreshPositions = async (): Promise<void> => { try { const prices = new Map(watchlist.map((pair) => [pair.symbol, pair.price])); prices.set(selectedSymbol, currentPrice); const uniqueSymbols = [...new Set(openPositions.map((position) => position.symbol))]; const specs = await Promise.all(uniqueSymbols.map(async (symbol) => { if (symbol === selectedSymbol && symbolSpec) return [symbol, symbolSpec] as const; if (symbolSpecCache.current[symbol]) return [symbol, symbolSpecCache.current[symbol]] as const; const spec = await marketDataSource.getSymbolSpec(symbol); symbolSpecCache.current[symbol] = spec; return [symbol, spec] as const })); if (cancelled) return; const specMap = new Map(specs); const updated = openPositions.map((position) => { const spec = specMap.get(position.symbol); const price = prices.get(position.symbol); if (!spec || !price) return position; const rate = getConversionRate(spec.quoteCurrency, accountData.currency); return markSimulatedPosition(position, { currentPrice: price, symbolSpec: spec, conversionRate: rate }) }); const newlyClosed = updated.filter((position, index) => openPositions[index].status === 'open' && position.status === 'closed'); const stillOpen = updated.filter((position) => position.status === 'open'); const realized = newlyClosed.reduce((sum, position) => sum + (position.profit ?? 0), 0); if (newlyClosed.length > 0) { if (isSimulatorMode()) applyDemoProfit(realized); setOpenPositions(stillOpen); setTradeHistory((prev) => [...newlyClosed, ...prev]); newlyClosed.forEach((position) => pushToast(`Simulated ${position.type} ${position.symbol} closed automatically at its ${position.profit !== undefined && position.profit >= 0 ? 'target' : 'stop'}.`)) } else if (updated.some((position, index) => position.profit !== openPositions[index].profit)) setOpenPositions(updated); const floatingPL = stillOpen.reduce((sum, position) => sum + (position.profit ?? 0), 0); setAccountData((prev) => { if (!prev) return prev; const balance = newlyClosed.length > 0 && isSimulatorMode() ? Number((prev.balance + realized).toFixed(2)) : prev.balance; const equity = Number((balance + floatingPL).toFixed(2)); const freeMargin = Number((equity - prev.usedMargin).toFixed(2)); if (prev.balance === balance && prev.equity === equity && prev.floatingPL === floatingPL && prev.freeMargin === freeMargin) return prev; return { ...prev, balance, equity, floatingPL, freeMargin } }) } catch (err) { if (!cancelled) pushToast(err instanceof Error ? err.message : 'Unable to update open position values.') } }; void refreshPositions(); return () => { cancelled = true } }, [accountData?.currency, currentPrice, openPositions, pushToast, selectedSymbol, symbolSpec, watchlist])
  if (!accountData || !symbolSpec || !marketAnalysis || !aiAnalysis) return <div className="flex h-full items-center justify-center bg-shafx-bg text-shafx-text">Loading SHAFX Terminal...</div>
  const activePosition = openPositions.find((position) => position.symbol === selectedSymbol && position.status === 'open') ?? null
  const showMarket = mobileTab === 'market'; const showAgent = mobileTab === 'agent'; const showHistory = mobileTab === 'history'; const showAccount = mobileTab === 'account'; const liveControl = <DerivLiveControl symbol={selectedSymbol} timeframe={timeframe} onUpdate={handleLiveUpdate} onActiveChange={handleLiveActiveChange} />; const brokerMode = isBrokerMode()
  const botProps = { symbol: selectedSymbol, timeframe, candles: chartCandles, currentPrice: displayPrice, activePosition, tradeHistory, accountBalance: accountData.balance, accountCurrency: accountData.currency, symbolSpec, conversionRate, botPlan: user?.botPlan ?? 'FREE' as const, onBotOrder: handleBotOrder, onReviewSetup: reviewAISetup }
  return <div className="flex h-full flex-col overflow-hidden bg-shafx-bg text-shafx-text">
    <TopNav symbol={selectedSymbol} price={displayPrice} pricePrecision={symbolSpec.pricePrecision} timeframe={timeframe} onTimeframeChange={setTimeframe} pairs={watchlist} onSelectPair={setSelectedSymbol} view={mobileTab} />
    <main className="flex flex-1 flex-col overflow-y-auto pb-16 lg:flex-row lg:overflow-hidden lg:pb-0">
      <aside className="hidden w-56 flex-shrink-0 flex-col gap-4 border-r border-shafx-border p-3 lg:flex lg:overflow-y-auto"><div className="h-72 flex-shrink-0"><Watchlist pairs={watchlist} selectedPair={selectedSymbol} onSelectPair={setSelectedSymbol} /></div><AccountPanel account={accountData} /></aside>
      <section className={`${showMarket ? '' : 'hidden'} flex min-w-0 flex-1 flex-col lg:flex`}><div className="flex h-11 flex-shrink-0 items-center justify-between gap-3 border-b border-shafx-border px-3 sm:px-4"><span className="text-[11px] text-shafx-textMuted">{liveMarketActive ? 'Live market feed • Deriv' : brokerMode ? 'Broker-connected account • market analysis' : 'Demo market feed'}</span>{liveControl}</div><div className="min-h-[500px] flex-1 p-2 sm:min-h-[560px] sm:p-3 lg:min-h-[620px]"><CandlestickChart data={chartCandles} symbol={selectedSymbol} timeframe={timeframe} currentPrice={displayPrice} annotations={chartAnnotations} /></div><div className="space-y-3 p-3 sm:p-4"><MarketAnalysisPanel analysis={marketAnalysis} pricePrecision={symbolSpec.pricePrecision} /><div id="manual-trade" className="rounded-xl border border-shafx-border bg-shafx-surface p-3"><button type="button" onClick={() => setManualTradeOpen((open) => !open)} className="flex min-h-12 w-full items-center justify-between text-left"><span><span className="block text-[10px] uppercase tracking-wider text-shafx-textMuted">Manual trading</span><strong className="block text-sm">Place your own trade</strong></span><ChevronDown className={`h-5 w-5 text-shafx-textMuted transition-transform ${manualTradeOpen ? 'rotate-180' : ''}`} /></button>{manualTradeOpen && <div className="mt-2"><OrderPanel symbol={selectedSymbol} currentPrice={displayPrice} accountBalance={accountData.balance} accountCurrency={accountData.currency} symbolSpec={symbolSpec} conversionRate={conversionRate} onSubmitOrder={handleOrderSubmit} aiSetup={aiSetup} /></div>}</div></div></section>
      <aside className={`${showAgent ? '' : 'hidden'} flex w-full flex-shrink-0 flex-col gap-4 p-3 sm:p-4 lg:hidden`}><TradingAgentPanel {...botProps} /></aside>
      <aside className={`${showHistory ? '' : 'hidden'} flex w-full flex-shrink-0 flex-col gap-4 p-3 sm:p-4 lg:hidden`}><TradesPanel openPositions={openPositions} pendingOrders={pendingOrders} tradeHistory={tradeHistory} currentPrice={displayPrice} selectedSymbol={selectedSymbol} onClosePosition={handleClosePosition} /><PerformancePanel tradeHistory={tradeHistory} currency={accountData.currency} /><TradingJournalPanel tradeHistory={tradeHistory} currency={accountData.currency} /></aside>
      <aside className={`${showAccount ? '' : 'hidden'} flex w-full flex-shrink-0 flex-col gap-4 p-3 sm:p-4 lg:hidden`}><AccountPanel account={accountData} /></aside>
      <aside className="hidden w-72 flex-shrink-0 flex-col gap-4 border-l border-shafx-border p-3 lg:flex lg:overflow-y-auto"><MarketAnalysisPanel analysis={marketAnalysis} pricePrecision={symbolSpec.pricePrecision} /><TradingAgentPanel {...botProps} /><AIAssistantPanel symbol={selectedSymbol} timeframe={timeframe} candles={chartCandles} setup={aiSetup} onReviewSetup={reviewAISetup} /><ReplayPanel candles={candles} replayCount={replayCount || candles.length} onReplayCountChange={setReplayCount} /><BacktestPanel symbol={selectedSymbol} candles={candles} symbolSpec={symbolSpec} initialBalance={accountData.balance} accountCurrency={accountData.currency} conversionRate={conversionRate} /><PerformancePanel tradeHistory={tradeHistory} currency={accountData.currency} /><TradingJournalPanel tradeHistory={tradeHistory} currency={accountData.currency} /><div id="order-ticket"><OrderPanel symbol={selectedSymbol} currentPrice={displayPrice} accountBalance={accountData.balance} accountCurrency={accountData.currency} symbolSpec={symbolSpec} conversionRate={conversionRate} onSubmitOrder={handleOrderSubmit} aiSetup={aiSetup} /></div></aside>
    </main><MobileNav activeTab={mobileTab} onChange={setMobileTab} /><footer className="hidden items-center justify-between border-t border-shafx-border bg-shafx-surface px-4 py-1.5 text-[10px] text-shafx-textMuted lg:flex"><span>SHAFX Terminal v0.1.0 • {brokerMode ? 'Broker-connected view • Real execution disabled' : 'Simulator Mode • No real money trading'}</span><span className="hidden sm:inline">{replayActive ? 'Visual replay — simulated candles only' : brokerMode ? 'Broker balance is read from the connected account' : 'Demo data only — not financial advice'}</span></footer><Toast toast={toast} onDismiss={() => setToast(null)} />
  </div>
}

const App: React.FC = () => <ErrorBoundary><TerminalProvider><TerminalContent /></TerminalProvider></ErrorBoundary>
export default App