-- Durable multi-provider connection/account registry and server-only provider secret references.

create table if not exists public.shafx_provider_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider_id text not null,
  label text not null default '',
  environment text not null default 'mixed' check (environment in ('demo','live','mixed')),
  state text not null default 'disconnected' check (state in ('connected','expired','disconnected','error')),
  auth_method text not null default 'oauth2' check (auth_method in ('oauth2','api_key','pat','custom')),
  credential_ref uuid,
  provider_subject text,
  expires_at timestamptz,
  last_seen_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists shafx_provider_connections_user_idx on public.shafx_provider_connections (user_id, created_at desc);
create index if not exists shafx_provider_connections_provider_idx on public.shafx_provider_connections (provider_id, state);

create table if not exists public.shafx_provider_accounts (
  id uuid primary key default gen_random_uuid(),
  connection_id uuid not null references public.shafx_provider_connections(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider_id text not null,
  provider_account_id text not null,
  label text,
  environment text not null check (environment in ('demo','live')),
  currency text,
  balance numeric,
  equity numeric,
  used_margin numeric,
  free_margin numeric,
  floating_pl numeric,
  active boolean not null default true,
  last_synced_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider_id, provider_account_id, environment)
);

create index if not exists shafx_provider_accounts_connection_idx on public.shafx_provider_accounts (connection_id, active);
create index if not exists shafx_provider_accounts_user_idx on public.shafx_provider_accounts (user_id, provider_id, environment);

create table if not exists public.shafx_provider_order_intents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  connection_id uuid not null references public.shafx_provider_connections(id) on delete restrict,
  account_id uuid not null references public.shafx_provider_accounts(id) on delete restrict,
  client_order_id text not null,
  provider_order_id text,
  state text not null default 'unknown' check (state in ('accepted','rejected','unknown','reconciled','cancelled')),
  request jsonb not null default '{}'::jsonb,
  result jsonb,
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, client_order_id)
);

create index if not exists shafx_provider_order_intents_account_idx on public.shafx_provider_order_intents (account_id, created_at desc);
create index if not exists shafx_provider_order_intents_user_idx on public.shafx_provider_order_intents (user_id, created_at desc);

create table if not exists public.shafx_provider_audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  connection_id uuid references public.shafx_provider_connections(id) on delete set null,
  account_id uuid references public.shafx_provider_accounts(id) on delete set null,
  event_type text not null,
  severity text not null default 'info' check (severity in ('info','warning','error','critical')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists shafx_provider_audit_events_user_idx on public.shafx_provider_audit_events (user_id, created_at desc);
create index if not exists shafx_provider_audit_events_connection_idx on public.shafx_provider_audit_events (connection_id, created_at desc);

create or replace function public.set_shafx_provider_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_shafx_provider_connection_updated on public.shafx_provider_connections;
create trigger on_shafx_provider_connection_updated before update on public.shafx_provider_connections for each row execute procedure public.set_shafx_provider_updated_at();
drop trigger if exists on_shafx_provider_account_updated on public.shafx_provider_accounts;
create trigger on_shafx_provider_account_updated before update on public.shafx_provider_accounts for each row execute procedure public.set_shafx_provider_updated_at();
drop trigger if exists on_shafx_provider_order_intent_updated on public.shafx_provider_order_intents;
create trigger on_shafx_provider_order_intent_updated before update on public.shafx_provider_order_intents for each row execute procedure public.set_shafx_provider_updated_at();

alter table public.shafx_provider_connections enable row level security;
alter table public.shafx_provider_accounts enable row level security;
alter table public.shafx_provider_order_intents enable row level security;
alter table public.shafx_provider_audit_events enable row level security;

drop policy if exists "No direct client access to SHAFX provider connections" on public.shafx_provider_connections;
create policy "No direct client access to SHAFX provider connections" on public.shafx_provider_connections for all to anon, authenticated using (false) with check (false);
drop policy if exists "No direct client access to SHAFX provider accounts" on public.shafx_provider_accounts;
create policy "No direct client access to SHAFX provider accounts" on public.shafx_provider_accounts for all to anon, authenticated using (false) with check (false);
drop policy if exists "No direct client access to SHAFX provider order intents" on public.shafx_provider_order_intents;
create policy "No direct client access to SHAFX provider order intents" on public.shafx_provider_order_intents for all to anon, authenticated using (false) with check (false);
drop policy if exists "No direct client access to SHAFX provider audit events" on public.shafx_provider_audit_events;
create policy "No direct client access to SHAFX provider audit events" on public.shafx_provider_audit_events for all to anon, authenticated using (false) with check (false);

alter function public.set_shafx_provider_updated_at() set search_path = '';

create or replace function public.create_shafx_provider_secret(p_secret text, p_name text, p_description text default null)
returns uuid language plpgsql security definer set search_path = public, vault as $$
declare v_id uuid;
begin
  if current_user not in ('service_role','supabase_admin','postgres') then raise exception 'provider secret storage is service-only'; end if;
  if coalesce(length(trim(p_secret)),0) < 16 then raise exception 'provider secret is too short'; end if;
  select vault.create_secret(p_secret, p_name, p_description) into v_id;
  return v_id;
end;
$$;

create or replace function public.read_shafx_provider_secret(p_secret_id uuid)
returns text language plpgsql security definer set search_path = public, vault as $$
declare v_secret text;
begin
  if current_user not in ('service_role','supabase_admin','postgres') then raise exception 'provider secret reads are service-only'; end if;
  select decrypted_secret into v_secret from vault.decrypted_secrets where id = p_secret_id;
  if v_secret is null then raise exception 'provider secret not found'; end if;
  return v_secret;
end;
$$;

create or replace function public.delete_shafx_provider_secret(p_secret_id uuid)
returns boolean language plpgsql security definer set search_path = public, vault as $$
begin
  if current_user not in ('service_role','supabase_admin','postgres') then raise exception 'provider secret deletion is service-only'; end if;
  delete from vault.secrets where id = p_secret_id;
  return found;
end;
$$;

revoke execute on function public.set_shafx_provider_updated_at() from public, anon, authenticated;
revoke execute on function public.create_shafx_provider_secret(text,text,text) from public, anon, authenticated;
revoke execute on function public.read_shafx_provider_secret(uuid) from public, anon, authenticated;
revoke execute on function public.delete_shafx_provider_secret(uuid) from public, anon, authenticated;

grant execute on function public.set_shafx_provider_updated_at() to service_role;
grant execute on function public.create_shafx_provider_secret(text,text,text) to service_role;
grant execute on function public.read_shafx_provider_secret(uuid) to service_role;
grant execute on function public.delete_shafx_provider_secret(uuid) to service_role;
