create table if not exists public.shafx_bot_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  connection_id uuid not null references public.shafx_provider_connections(id) on delete restrict,
  account_row_id uuid not null references public.shafx_provider_accounts(id) on delete restrict,
  symbol text not null,
  stake numeric(18,8) not null check (stake >= 10 and stake <= 2000),
  multiplier_mode text not null default 'auto' check (multiplier_mode in ('auto','manual')),
  multiplier numeric(18,8),
  plan text not null default 'FREE' check (plan in ('FREE','REGULAR','PRO')),
  unit_number integer not null default 1 check (unit_number >= 1),
  current_round integer not null default 0 check (current_round between 0 and 5),
  completed_rounds integer not null default 0 check (completed_rounds between 0 and 5),
  status text not null default 'queued' check (status in ('queued','scanning','waiting','buying','open','closing','completed','stopped','cancel_requested','failed')),
  next_action_at timestamptz not null default now(),
  locked_by text,
  locked_until timestamptz,
  cancel_requested boolean not null default false,
  total_profit numeric(18,8) not null default 0,
  total_loss numeric(18,8) not null default 0,
  net_profit numeric(18,8) not null default 0,
  last_error text,
  started_at timestamptz,
  completed_at timestamptz,
  last_heartbeat_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists shafx_bot_runs_worker_idx on public.shafx_bot_runs (status, next_action_at, locked_until, created_at);
create index if not exists shafx_bot_runs_user_idx on public.shafx_bot_runs (user_id, created_at desc);
create unique index if not exists shafx_bot_runs_one_active_per_account_idx on public.shafx_bot_runs (user_id, account_row_id)
  where status in ('queued','scanning','waiting','buying','open','closing','cancel_requested');

create table if not exists public.shafx_bot_rounds (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.shafx_bot_runs(id) on delete cascade,
  round_number integer not null check (round_number between 1 and 5),
  status text not null default 'queued' check (status in ('queued','scanning','waiting','buying','open','closing','won','loss','failed','stopped')),
  signal_direction text check (signal_direction in ('BUY','SELL','WAIT')),
  signal_strength numeric(6,2),
  signal_timeframe text,
  signal_snapshot jsonb not null default '{}'::jsonb,
  proposal_id text,
  contract_id text,
  stake numeric(18,8),
  multiplier numeric(18,8),
  entry_price numeric(30,12),
  exit_price numeric(30,12),
  profit numeric(18,8),
  max_profit numeric(18,8),
  max_loss numeric(18,8),
  opened_at timestamptz,
  closed_at timestamptz,
  next_check_at timestamptz,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_id, round_number)
);

create index if not exists shafx_bot_rounds_run_idx on public.shafx_bot_rounds (run_id, round_number);
create index if not exists shafx_bot_rounds_contract_idx on public.shafx_bot_rounds (contract_id) where contract_id is not null;

create table if not exists public.shafx_bot_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.shafx_bot_runs(id) on delete cascade,
  round_id uuid references public.shafx_bot_rounds(id) on delete set null,
  event_type text not null,
  severity text not null default 'info' check (severity in ('info','warning','error','critical')),
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists shafx_bot_events_run_idx on public.shafx_bot_events (run_id, created_at desc);

create or replace function public.set_shafx_bot_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_shafx_bot_run_updated on public.shafx_bot_runs;
create trigger on_shafx_bot_run_updated before update on public.shafx_bot_runs for each row execute procedure public.set_shafx_bot_updated_at();
drop trigger if exists on_shafx_bot_round_updated on public.shafx_bot_rounds;
create trigger on_shafx_bot_round_updated before update on public.shafx_bot_rounds for each row execute procedure public.set_shafx_bot_updated_at();

alter table public.shafx_bot_runs enable row level security;
alter table public.shafx_bot_rounds enable row level security;
alter table public.shafx_bot_events enable row level security;

drop policy if exists "No direct client access to SHAFX bot runs" on public.shafx_bot_runs;
create policy "No direct client access to SHAFX bot runs" on public.shafx_bot_runs for all to anon, authenticated using (false) with check (false);
drop policy if exists "No direct client access to SHAFX bot rounds" on public.shafx_bot_rounds;
create policy "No direct client access to SHAFX bot rounds" on public.shafx_bot_rounds for all to anon, authenticated using (false) with check (false);
drop policy if exists "No direct client access to SHAFX bot events" on public.shafx_bot_events;
create policy "No direct client access to SHAFX bot events" on public.shafx_bot_events for all to anon, authenticated using (false) with check (false);

create or replace function public.claim_shafx_bot_run(p_worker text)
returns table (
  id uuid,
  user_id uuid,
  connection_id uuid,
  account_row_id uuid,
  symbol text,
  stake numeric,
  multiplier_mode text,
  multiplier numeric,
  plan text,
  unit_number integer,
  current_round integer,
  completed_rounds integer,
  status text,
  next_action_at timestamptz,
  cancel_requested boolean,
  total_profit numeric,
  total_loss numeric,
  net_profit numeric,
  locked_until timestamptz
)
language plpgsql security definer set search_path = public as $$
declare v_run public.shafx_bot_runs;
begin
  if current_user not in ('service_role','supabase_admin','postgres') then
    raise exception 'bot worker claim is service-only';
  end if;

  select * into v_run
  from public.shafx_bot_runs
  where status in ('queued','scanning','waiting','buying','open','closing','cancel_requested')
    and next_action_at <= now()
    and (locked_until is null or locked_until < now())
  order by next_action_at asc, created_at asc
  for update skip locked
  limit 1;

  if not found then return; end if;

  update public.shafx_bot_runs
     set locked_by = p_worker,
         locked_until = now() + interval '20 seconds',
         last_heartbeat_at = now(),
         status = case when status = 'queued' then 'scanning' else status end
   where public.shafx_bot_runs.id = v_run.id
   returning * into v_run;

  return query
  select v_run.id, v_run.user_id, v_run.connection_id, v_run.account_row_id, v_run.symbol,
         v_run.stake, v_run.multiplier_mode, v_run.multiplier, v_run.plan, v_run.unit_number,
         v_run.current_round, v_run.completed_rounds, v_run.status, v_run.next_action_at,
         v_run.cancel_requested, v_run.total_profit, v_run.total_loss, v_run.net_profit, v_run.locked_until;
end;
$$;

revoke execute on function public.set_shafx_bot_updated_at() from public, anon, authenticated;
revoke execute on function public.claim_shafx_bot_run(text) from public, anon, authenticated;
grant execute on function public.set_shafx_bot_updated_at() to service_role;
grant execute on function public.claim_shafx_bot_run(text) to service_role;
